Option Strict Off
Option Explicit On
Friend Class Form6
	Inherits System.Windows.Forms.Form

    Private Sub cmdHelpArcTime_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpArcTime.Click
        'cmdHelpGeneral.Font = vb6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, True)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpArcTime.BringToFront()
    End Sub

    Private Sub cmdHelpAveraging_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpAveraging.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, True)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpAveraging.BringToFront()
	End Sub
	
	Private Sub cmdHelpCurrents_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpCurrents.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, True)
        txtHelpCurrents.BringToFront()
	End Sub
	
	Private Sub cmdHelpFavorites_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpFavorites.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, True)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpFavorites.BringToFront()
	End Sub
	
	Private Sub cmdHelpGeneral_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpGeneral.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, True)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpGeneral.BringToFront()
	End Sub
	
	Private Sub cmdHelpLength_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpLength.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, True)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpLength.BringToFront()
	End Sub
	
	Private Sub cmdHelpLoCNASR_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpLoCNASR.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, True)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpLoCNASR.BringToFront()
	End Sub
	
	Private Sub cmdHelpNoon_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpNoon.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, True)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpNoon.BringToFront()
	End Sub
	
	Private Sub cmdHelpPlan_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpPlan.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, True)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpPlan.BringToFront()
	End Sub
	
	Private Sub cmdHelpSRF_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpSRF.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, True)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpSRF.BringToFront()
	End Sub
	Private Sub cmdHelpSailings_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpSailings.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, True)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpSailings.BringToFront()
	End Sub
	Private Sub cmdHelpCTS_SOA_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpCTS_SOA.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, True)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpCTS_SOA.BringToFront()
	End Sub
	Private Sub cmdHelpDistances_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpDistances.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, True)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpDistances.BringToFront()
	End Sub
	
	Private Sub cmdHelpInterpolate_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpInterpolate.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, True)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpInterpolate.BringToFront()
	End Sub
	Private Sub cmdHelp60DST_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelp60DST.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, True)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelp60DST.BringToFront()
	End Sub
	Private Sub cmdHelpTides_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpTides.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, True)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpTides.BringToFront()
	End Sub
	Private Sub cmdHelpTVMDC_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpTVMDC.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, True)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpTVMDC.BringToFront()
	End Sub
	
	Private Sub cmdHelpTwoBearings_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpTwoBearings.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, True)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpTwoBearings.BringToFront()
	End Sub
	
	Private Sub cmdHelpYellow_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpYellow.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, True)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, False)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpYellow.BringToFront()
	End Sub
	Private Sub cmdHelpMoBoard_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdHelpMoBoard.Click
        'cmdHelpGeneral.Font = VB6.FontChangeBold(cmdHelpGeneral.Font, False)
        'cmdHelpCTS_SOA.Font = VB6.FontChangeBold(cmdHelpCTS_SOA.Font, False)
        'cmdHelpPlan.Font = VB6.FontChangeBold(cmdHelpPlan.Font, False)
        'cmdHelpSRF.Font = VB6.FontChangeBold(cmdHelpSRF.Font, False)
        'cmdHelpNoon.Font = VB6.FontChangeBold(cmdHelpNoon.Font, False)
        'cmdHelpYellow.Font = VB6.FontChangeBold(cmdHelpYellow.Font, False)
        'cmdHelpFavorites.Font = VB6.FontChangeBold(cmdHelpFavorites.Font, False)
        'cmdHelpLoCNASR.Font = VB6.FontChangeBold(cmdHelpLoCNASR.Font, False)
        'cmdHelpAveraging.Font = VB6.FontChangeBold(cmdHelpAveraging.Font, False)
        'cmdHelpArcTime.Font = VB6.FontChangeBold(cmdHelpArcTime.Font, False)
        'cmdHelpSailings.Font = VB6.FontChangeBold(cmdHelpSailings.Font, False)
        'cmdHelpDistances.Font = VB6.FontChangeBold(cmdHelpDistances.Font, False)
        'cmdHelpInterpolate.Font = VB6.FontChangeBold(cmdHelpInterpolate.Font, False)
        'cmdHelp60DST.Font = VB6.FontChangeBold(cmdHelp60DST.Font, False)
        'cmdHelpTVMDC.Font = VB6.FontChangeBold(cmdHelpTVMDC.Font, False)
        'cmdHelpLength.Font = VB6.FontChangeBold(cmdHelpLength.Font, False)
        'cmdHelpMoBoard.Font = VB6.FontChangeBold(cmdHelpMoBoard.Font, True)
        'cmdHelpTwoBearings.Font = VB6.FontChangeBold(cmdHelpTwoBearings.Font, False)
        'cmdHelpTides.Font = VB6.FontChangeBold(cmdHelpTides.Font, False)
        'cmdHelpCurrents.Font = VB6.FontChangeBold(cmdHelpCurrents.Font, False)
        txtHelpMoBoard.BringToFront()
	End Sub
	
	Private Sub cmdPrint_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdPrint.Click
		frmPrintHelp.Show()
		'    Printer.Print Form6.txtHelpGeneral.Text
		'    Printer.Print Form6.txtHelpPlan.Text
		'    Printer.Print Form6.txtHelpSRF.Text
		'    Printer.Print Form6.txtHelpNoon.Text
		'    Printer.Print Form6.txtHelpLoCNASR.Text
		'    Printer.Print Form6.txtHelpAveraging.Text
		'    Printer.Print Form6.txtHelpCTS_SOA.Text
		'    Printer.Print Form6.txtHelpArcTime.Text
		'    Printer.Print Form6.txtHelpSailings.Text
		'    Printer.Print Form6.txtHelpDistances.Text
		'    Printer.Print Form6.txtHelpInterpolate.Text
		'    Printer.Print Form6.txtHelp60DST.Text
		'    Printer.Print Form6.txtHelpTVMDC.Text
		'    Printer.Print Form6.txtHelpLength.Text
		'    Printer.Print Form6.txtHelpFavorites.Text
		'    Printer.EndDoc
	End Sub
	
	Private Sub Form6_Load(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles MyBase.Load
		cmdHelpGeneral_Click(cmdHelpGeneral, New System.EventArgs())
	End Sub
	
	Private Sub Form6_FormClosed(ByVal eventSender As System.Object, ByVal eventArgs As System.Windows.Forms.FormClosedEventArgs) Handles Me.FormClosed
		Cleanup()
	End Sub
End Class